### ISSUE TITLE
Why `org.pantsbuild.jarjar.util.JarProcessor` has a package private `process` method ?

### ISSUE THREAD

**Issue by wxiang7** [pantsbuild/jarjar#1]
Why `org.pantsbuild.jarjar.util.JarProcessor` has a package private `process` method ?
However the `MainProcessor` which implement `JarProcessor` has a public `process` method.

And why `MainProcessor` is package private ?
If I want to use it from another project, how can I manage to do that ?

thanks
wu

**Comment by jsirois** [comment]
Most importantly, as the [README](https://github.com/pantsbuild/jarjar/blob/master/README.md) states, this is an export of the google code project for _pants own use_.  We don't intend other projects to use it.

Now if I read into the original authors' intents, my guess is they are very careful about the public API they expose on purpose (see: [Effective Java](http://www.amazon.com/Effective-Java-Edition-Joshua-Bloch/dp/0321356683) Item 13: Minimize the accessibility of classes and members).  As such, they only expose JarJarMojo (maven plugin), JarJarTask (ant task), and the Main for command line use.  I can't say I blame them.

To finish, I'll underscore that we are not maintainers of the primary jarjar and we do not support any project using our jarjar fork except for https://github.com/pantsbuild/pants.  You might try to contact the the original and official project members listed on googlecode: https://code.google.com/p/jarjar/

**Comment by jsirois** [comment]
For what it's worth, pants gets along by just using the JarJar main, and, by default, running jarjar in a nailgun to eliminate the startup overhead.
