### ISSUE TITLE
Produce an all-deps artifact of jarjar

### ISSUE THREAD

**Issue by ronshapiro** [pantsbuild/jarjar#25]
Since there are lots of deps for jarjar, it makes it challenging to run from the command-line. Can you use the maven-shade-plugin to create a version of the build that bundles all the deps together? Google Java Format does this and it's [relatively trivial](https://github.com/google/google-java-format/blob/d3d9a9c0ed06e659065ff4214c28a5c2442b3019/core/pom.xml#L106-L135). Happy to send a pull-request if you'd like.

**Comment by ronshapiro** [comment]
Hm, I didn't realize that pants was generating the POM, so this might be more complicated than I thought.

**Comment by jsirois** [comment]
Regardless, as our README states, we maintain this clone of the original jarjar google code project strictly for pants use. It is trivial fwiw to run jarjar using pants. This BUILD file:
```
jar_library(
  name='jarjar',
  jars=[
    jar('org.pantsbuild', 'jarjar', '1.6.3'),
  ]
)

jvm_binary(
  name='jarjar-main',
  dependencies=[
    ': jarjar',
  ],
  main='org.pantsbuild.jarjar.Main',
)
```

Can be run with: `./pants run //:jarjar-main -- [jarjar args]`

**Comment by jsirois** [comment]
Using the BUILD file above you can also create a runnable fat jar with: `./pants binary //:jarjar-main`. The all-inclusive jar will be plopped in dist and you can run with: `java -jar dist/jarjar-main.jar ...`.  We would never publish a fat jar though  out of principle.
