### ISSUE TITLE
Update ASM dependency

### ISSUE THREAD

**Issue by pomadchin** [pantsbuild/jarjar#26]
In `asm 5.0.x` there is a bug: https://github.com/sbt/sbt-assembly/issues/205#issuecomment-278287602 can you release `1.6.4` with asm updated up to `5.2`? [Current possible workaround](https://github.com/sbt/sbt-assembly/pull/237).

**Comment by jsirois** [comment]
#27 has been merged and released to maven central - should show up within the next few hours. At that point I'll send an upgrade PR for https://github.com/pantsbuild/pants to bump to 1.6.4 and close out this issue.

**Comment by pomadchin** [comment]
@jsirois thank you!
