### ISSUE TITLE
Jarjar doesn't work with classfile from scala

### ISSUE THREAD

**Issue by Dao007forever** [pantsbuild/jarjar#29]
We ran into an issue where we can't shade classfiles produced by scalac.
I made an example here: https://github.com/Dao007forever/testjarjar.
It tries to change "com.abc" -> "com.aaa"

After running `sbt assembly`, inspecting the shaded classfile in IntelliJ shows traces of "com.abc".
Inspecting the classfile using `javap -v -c -l` doesn't show "com.abc".

Trying to use scalac to compile `TestShade.scala` in the root directory failed:
```
scalac -classpath target/scala-2.11/test-assembly-0.1-SNAPSHOT.jar TestShade.scala
```
Trying to use javac to compile `TestShade.java` succeeded:
```
javac -classpath target/scala-2.11/test-assembly-0.1-SNAPSHOT.jar TestShade.java
```

**Comment by jsirois** [comment]
Was this issue encountered when using [Pants](pantsbuild.org) to do your shading? If not, as the [README](https://github.com/pantsbuild/jarjar/blob/master/README.md) mentions, this repo only exists to support Pants and we don't have the bandwidth to support general use.

**Comment by jsirois** [comment]
Your example project appears to use sbt, so I'll close out this issue assuming this is not a Pants-supported use case. Please re-open if I'm mistaken and good luck in your shading quest regardless!
